name: OpenSCAP Compliance Check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create results directory
      run: mkdir -p results

    - name: Build Docker image
      run: docker build . -t openscap-check

    - name: Run OpenSCAP compliance check
      run: |
        docker run --name openscap-container \
        -v ${{ github.workspace }}/results:/results \
        openscap-check

    - name: List results for debugging
      run: ls -lah results/

    - name: Upload Results as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: openscap-results
        path: results/


